### ISSUE TITLE
Not compatible with 16:9 aspect ratio

### ISSUE THREAD

**Issue by spitzbubchen** [michaelkirker/Unofficial-UChicago-Beamer-Theme#2]
Nice work! Would like to use, however, the conference where I'm presenting uses HD 16:9 format.

Tried

`\documentclass[aspectratio=169]{beamer}`

however, this messes up the graphics.

**Comment by michaelkirker** [comment]
Thanks for the feedback. I have had a brief look into the issue just now as the only projectors I have encountered have been the 4:3 versions. It seems to me that the major issue is the graphic on the title page remains in its absolute position, and doesnt scale to the new aspect ratio. There is also a minor issue that the shield in the title bar also shifts slightly tight cutting down on the spacing to the right hand side). 

I already have an idea of how I can fix the graphic on the title page (the main issue). It should be a relatively straight forward fix. The minor issue of the graphics in the title bar should be do-able as well, but might take a bit longer as it is more fiddly. I'll try to get these sorted asap.

When is the conference? Fixing the title graphics in time should easily be doable. And if the graphics in the title bar cannot be fixed, it is possible to suppress those (most people dont notice them anyway).

**Comment by spitzbubchen** [comment]
Presentation is next week Monday. Thanks for looking into it.

**Comment by michaelkirker** [comment]
I just pushed an updated build that should have the graphics scaling correctly when using the 16:9 aspect ratio (as well as any other aspect ratio, but I am yet to test those). Please check to see if the latest version addresses the problems you were having.

**Comment by spitzbubchen** [comment]
Looks great! Thanks!
